### PR TITLE
(hotfix): fix monitoring links

### LINKED ISSUE #51: Monitoring application link on successful deployment / start instance not working
### Describe the bug

When deploying a model / starting a process the link to the monitoring app is not working

### Steps to reproduce

1. Deploy model
2. Click on popup to redirect to deployment in monitoring app
3. Land on error page

### Expected behavior

Link should redirect to the deployment / instance successfully

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Fluxnova Modeler Version: [e.g. 1.0.0]
- Execution Platform: [e.g. Fluxnova 1]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by daraghhiggins12**
* Monitoring link now working as expected and redirects to deployment / process instance successfully
* Security Fix: Puppeteer upgraded from 24.0.0 to 24.28.0

closes #51

### CODE REVIEW

File: client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ describe('<webAppUrls>', function() {
       const cockpitUrl = await determineCockpitUrl('http://localhost:8080/camunda/rest');
```
Comment (gliptak) [inline client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js]: are we specifically keeping `camunda` in this URL?

File: client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js [hunk 2]
```diff
@@ -64,7 +64,7 @@ describe('<webAppUrls>', function() {
...
```
Comment (gliptak) [inline client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js]: are we specifically keeping `camunda` in this URL?

File: client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js (hunk 1 above)
Comment (daraghhiggins12) [reply client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js]: Addressed

File: client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js (hunk 2 above)
Comment (daraghhiggins12) [reply client/src/plugins/camunda-plugin/shared/__tests__/webAppUrlsSpec.js]: Addressed

**Review by pieter-schutte — APPROVED** [review]

**Comment by daraghhiggins12** [comment]
Looking for one more approval and merge @gliptak @finos/fluxnova-maintainers

**Review by gliptak — APPROVED** [review]
